// Prices marked with + on the website indicate starting prices that may vary.
// Durations are estimated — adjust based on Tania's actual booking times.
module.exports = [
  {
    id: "bang-trim",
    name: "Bang Trim",
    duration: 15,
    price: 25,
    category: "Haircuts",
    description: "Quick bang trim — complimentary for existing clients booking a haircut",
  },
  {
    id: "womens-haircut",
    name: "Woman's Haircut",
    duration: 45,
    price: 65,
    category: "Haircuts",
    description: "Precision cut tailored to your facial structure and preferences",
  },
  {
    id: "mens-haircut",
    name: "Man's Haircut",
    duration: 30,
    price: 40,
    category: "Haircuts",
    description: "Clean, styled haircut",
  },
  {
    id: "cut-blowdry-style",
    name: "Cut, Blowdry & Style",
    duration: 75,
    price: 85,
    category: "Haircuts",
    description: "Woman's haircut with professional blowdry and styling finish",
  },
  {
    id: "roots-touch-up",
    name: "Roots Touch Up",
    duration: 60,
    price: 50,
    category: "Color",
    description: "Single-process color applied to regrowth — starting price",
  },
  {
    id: "regular-coloring",
    name: "Regular Coloring",
    duration: 90,
    price: 75,
    category: "Color",
    description: "Full single-process color — starting price",
  },
  {
    id: "full-highlights",
    name: "Full Highlights",
    duration: 150,
    price: 170,
    category: "Color",
    description: "Full head highlights — starting price",
  },
  {
    id: "partial-highlights",
    name: "Partial Highlights",
    duration: 120,
    price: 120,
    category: "Color",
    description: "Partial highlights framing the face and top — starting price",
  },
  {
    id: "baby-highlights",
    name: "Baby Highlights",
    duration: 120,
    price: 120,
    category: "Color",
    description: "Subtle, fine highlights for a natural sun-kissed effect — starting price",
  },
  {
    id: "balayage",
    name: "Balayage",
    duration: 180,
    price: 199,
    category: "Color",
    description: "Freehand-painted balayage for a seamless, dimensional look — starting price",
  },
  {
    id: "amber-hair",
    name: "Amber Hair",
    duration: 180,
    price: 210,
    category: "Color",
    description: "Signature warm amber tones — starting price",
  },
  {
    id: "color-correction",
    name: "Color Correction",
    duration: 240,
    price: 85,
    category: "Color",
    description: "Corrective color service — consultation strongly recommended. Starting price.",
  },
  {
    id: "hair-toner",
    name: "Hair Toner",
    duration: 45,
    price: 85,
    category: "Color",
    description: "Toner to neutralize brassiness and refine color — starting price",
  },
];
