module.exports = [
  {
    id: "haircut-blowout",
    name: "Haircut & Blowout",
    duration: 60, // minutes
    price: 85,
    category: "Hair",
    description: "Precision cut with professional blowout finish",
  },
  {
    id: "color-full",
    name: "Full Color",
    duration: 120,
    price: 150,
    category: "Color",
    description: "Full head single-process color",
  },
  {
    id: "color-highlights",
    name: "Highlights",
    duration: 150,
    price: 180,
    category: "Color",
    description: "Partial or full highlights with toner",
  },
  {
    id: "balayage",
    name: "Balayage",
    duration: 180,
    price: 220,
    category: "Color",
    description: "Hand-painted balayage technique",
  },
  {
    id: "blowout",
    name: "Blowout",
    duration: 45,
    price: 55,
    category: "Styling",
    description: "Professional blowout without cut",
  },
  {
    id: "updo",
    name: "Updo / Special Occasion",
    duration: 75,
    price: 95,
    category: "Styling",
    description: "Formal updo or special event styling",
  },
  {
    id: "deep-conditioning",
    name: "Deep Conditioning Treatment",
    duration: 30,
    price: 45,
    category: "Treatment",
    description: "Intensive moisture and repair treatment",
  },
  {
    id: "keratin",
    name: "Keratin Treatment",
    duration: 180,
    price: 300,
    category: "Treatment",
    description: "Smoothing keratin treatment, lasts 3-5 months",
  },
];
